### ISSUE TITLE
I wrote a blog featuring your component

### ISSUE THREAD

**Issue by binbalenci** [MaritzSTL/mtz-update-password#8]
Hi,

Last week, I wrote a blog "Top five password inputs" featuring your component. We think that mtz-update-password is really cool.

Check out the blog here -> https://vaadin.com/blog/top-five-web-components-for-password-inp-1

It would be awesome if you can drop a quick comment in the comment section below, or on this [tweet](https://twitter.com/slashpiggie/status/983992620664926208) so that people can know who the mastermind is. 

Cheers!

**Comment by admwx7** [comment]
Fixed the issues you pointed out: https://github.com/MaritzSTL/mtz-update-password/pull/9

**Comment by stramel** [comment]
@haydenmcp @ZempTime @jay8t6 Would be cool to add a link to the post in the `README.md`

**Comment by jay8t6** [comment]
Will do.

**Comment by jay8t6** [comment]
Closing this.
